# Generated by Django 5.2.3 on 2025-07-02 07:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0010_company_tin'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Numer faktury')),
                ('issue_date', models.DateField(verbose_name='Data wystawienia')),
                ('due_date', models.DateField(verbose_name='Data płatności')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('sent', 'Wysłana'), ('paid', 'Zapłacona'), ('overdue', 'Przeterminowana'), ('cancelled', 'Anulowana')], default='draft', max_length=20, verbose_name='Status')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota netto')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota VAT')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota brutto')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='Nazwa dostawcy')),
                ('supplier_tax_id', models.CharField(max_length=20, verbose_name='NIP dostawcy')),
                ('supplier_address', models.CharField(max_length=255, verbose_name='Adres dostawcy')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Faktura kosztowa',
                'verbose_name_plural': 'Faktury kosztowe',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255, verbose_name='Opis')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ilość')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cena jednostkowa')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cena całkowita')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('23.00'), max_digits=5, verbose_name='Stawka VAT')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Pozycja faktury',
                'verbose_name_plural': 'Pozycje faktur',
            },
        ),
        migrations.CreateModel(
            name='RevenueInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Numer faktury')),
                ('issue_date', models.DateField(verbose_name='Data wystawienia')),
                ('due_date', models.DateField(verbose_name='Data płatności')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('sent', 'Wysłana'), ('paid', 'Zapłacona'), ('overdue', 'Przeterminowana'), ('cancelled', 'Anulowana')], default='draft', max_length=20, verbose_name='Status')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota netto')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota VAT')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota brutto')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nazwa klienta')),
                ('client_tax_id', models.CharField(max_length=20, verbose_name='NIP klienta')),
                ('client_address', models.CharField(max_length=255, verbose_name='Adres klienta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Faktura przychodowa',
                'verbose_name_plural': 'Faktury przychodowe',
            },
        ),
    ]
