# Generated by Django 5.2.3 on 2025-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='vat',
            field=models.BooleanField(default=False),
        ),
    ]
