# Generated by Django 5.2.3 on 2025-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0004_company_tax_value_company_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
        ),
    ]
