# Generated by Django 5.2.3 on 2025-06-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_tax_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('BA', 'Business activity'), ('LLC', 'Limited liability company'), ('JSC', 'Joint stock company')], default='BA', max_length=3, verbose_name='Company Type'),
        ),
    ]
