# Generated by Django 5.2.3 on 2025-06-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_company_type'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='company',
        #     name='name',
        #     field=models.CharField(max_length=100, unique=True),
        # ),
    ]
