# Generated by Django 5.2.3 on 2025-06-24 07:10

from django.db import migrations, models

def fix_company_name_duplications(app, schema_editor):
    Company = app.get_model("Companies", "Company")
    seen = set()

    for company in Company.objects.all().order_by('id'):
        if company.name in seen:
            # If the name is a duplicate, append a unique suffix
            suffix = 1
            new_name = f"{company.name} ({suffix})"
            while Company.objects.filter(name=new_name).exists():
                suffix += 1
                new_name = f"{company.name} ({suffix})"
            company.name = new_name
            company.save()
        seen.add(company.name)

class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0007_alter_company_name'),
    ]

    operations = [
        migrations.RunPython(fix_company_name_duplications, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
