# Generated by Django 5.2.3 on 2025-06-24 07:38

from django.db import migrations


def fix_company_data(apps, schema_editor):
    Company = apps.get_model('Companies', 'Company')
    # Assuming the fix is to set a default tax_value for companies without it
    companies = Company.objects.all()

    for company in companies:
        if company.tax_value < 0:
            company.tax_value = 12
        if company.company_type not in ["BA", "LLC", "JSC"]:
            company.company_type = "BA" # Set to first choice
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0008_auto_20250624_0910'),
    ]

    operations = [
        migrations.RunPython(fix_company_data, reverse_code=migrations.RunPython.noop),
    ]
